[package]
name = "bfcorr"
version = "0.1.0"
authors = ["Gu Junhua <jhgu@nao.cas.cn>"]

[dependencies]
udt = "0.2.0"
pcap = "0.7.0"
crossbeam-channel = "0.2.4"
num-complex = "0.2.0"
num-traits = "0.2.5"
rayon="1.0.2"
chrono="0.4.6"
endian_trait="0.6.0"

[dependencies.astroalgo]
path="../astroalgo"
